services:
  kcapp_db:
    image: linuxserver/mariadb:11.4.5
    hostname: kcapp-db
    container_name: kcapp-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: 'kcapp'
      MYSQL_USER: 'developer'
      MYSQL_PASSWORD: 'abcd1234'
      MYSQL_ROOT_PASSWORD: 'abcd1234'
    ports:
      - '3306:3306'
    expose:
      - '3366'
    volumes:
      - ./db/config:/config
      - ./db/data:/var/lib/mysql
